name: 功能建议
description: '如果你有一些新的点子，请通过此模板告诉我哦！'
title: "[建议] 简短的被描述"
labels: [建议]
body:
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: |
        请在这里详细地描述出你的好点子
    validations:
      required: true

  - type: textarea
    id: more-info
    attributes:
      label: 其他信息
      description: |
        如果可以的话，你也可以提供图片，帮助我更好的理解你的好想法
    validations:
      required: false

  - type: checkboxes
    id: check-issue
    attributes:
      label: 这个功能建议还没有人提出过
      options:
        - label: 我已经查看过 Issues，并且没有发现与之类似的功能建议被提出
          required: true