name: Feature Request
description: 'If you have any new ideas, please let me know using this template!'
title: "[Request] Brief Description"
labels: [建议]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: |
        Please describe your idea in detail here.
    validations:
      required: true

  - type: textarea
    id: more-info
    attributes:
      label: Additional Information
      description: |
        If possible, you can also provide images to help me better understand your idea.
    validations:
      required: false

  - type: checkboxes
    id: check-issue
    attributes:
      label: This feature request has not been proposed before
      options:
        - label: I have checked the Issues and found no similar feature request
          required: true
