name: Lwjgl3 Build
on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build JRE JAR files
        run: |
          # Build JRE JAR files (security manager, etc...)
          gradle :jre_lwjgl3glfw:build --no-daemon
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lwjgl
          path: lwjgl3/*
